# build_talent_affixes.ps1
# Reads talent_affixes/_maps.json (lookup maps) plus every
# talent_affixes/<Class>/*.json (per-spec definitions) and writes
# data/sql/db-world/talent_affix_def.sql.
#
# File layout:
#   talent_affixes/_maps.json            — lookup maps only (spell_family, class_mask, etc.)
#   talent_affixes/<Class>/<spec>.json   — per-spec entries for this class (spec_tree=0/1/2)
#
# removedTalentAffixes: IDs listed in "removedTalentAffixes" in any class file are deleted
# from talent_affix_def on each run, then active entries are upserted.
# Keep removed entries in the array for history; moving an entry back to "talent_affixes"
# restores it (DELETE runs before INSERT so the id is safe to reuse).
#
# Run via update_affixes.bat, or standalone: powershell -File build_talent_affixes.ps1

$ErrorActionPreference = "Stop"
$ScriptDir    = Split-Path -Parent $MyInvocation.MyCommand.Path
$TalentDir    = Join-Path $ScriptDir "talent_affixes"
$MapsJson     = Join-Path $TalentDir "_maps.json"
$OutPath      = Join-Path $ScriptDir "data\sql\db-world\talent_affix_def.sql"

# Read lookup maps from the dedicated maps file
Write-Host "  Reading $MapsJson ..."
$json = Get-Content $MapsJson -Raw | ConvertFrom-Json

# Build lookup tables from the json maps
$familyMap   = @{}; foreach ($prop in $json.spell_family_map.PSObject.Properties)  { $familyMap[$prop.Name]  = $prop.Value }
$classMaskMap= @{}; foreach ($prop in $json.class_mask_map.PSObject.Properties)    { $classMaskMap[$prop.Name] = $prop.Value }
$opMap       = @{}; foreach ($prop in $json.spellmod_op_map.PSObject.Properties)   { $opMap[$prop.Name]      = $prop.Value }
$typeMap     = @{}; foreach ($prop in $json.spellmod_type_map.PSObject.Properties) { $typeMap[$prop.Name]    = $prop.Value }

# Collect removedTalentAffixes IDs from _maps.json (global removals)
$allRemovedIds = [System.Collections.Generic.List[int]]::new()
if ($json.PSObject.Properties["removedTalentAffixes"]) {
    foreach ($r in $json.removedTalentAffixes) {
        if ($r.PSObject.Properties["id"]) { $allRemovedIds.Add([int]$r.id) }
    }
}

# Collect entries and removed IDs from all per-class/per-spec files under talent_affixes/<Class>/*.json
$allRaw = @()
$subFiles = Get-ChildItem $TalentDir -Recurse -Filter "*.json" |
    Where-Object { $_.FullName -ne $MapsJson } |
    Sort-Object { $_.FullName }
foreach ($f in $subFiles) {
    Write-Host "  Reading $($f.FullName.Replace($ScriptDir, '.')) ..."
    $sub = Get-Content $f.FullName -Raw | ConvertFrom-Json
    if ($sub.PSObject.Properties["talent_affixes"]) {
        $allRaw += @($sub.talent_affixes | Where-Object { $_.PSObject.Properties["id"] })
    }
    if ($sub.PSObject.Properties["removedTalentAffixes"]) {
        foreach ($r in $sub.removedTalentAffixes) {
            if ($r.PSObject.Properties["id"]) { $allRemovedIds.Add([int]$r.id) }
        }
    }
}

# Sort by id and check for duplicates
$talents = $allRaw | Sort-Object { [int]$_.id }
$dupIds  = $allRaw | Group-Object { $_.id } | Where-Object { $_.Count -gt 1 }
if ($dupIds) {
    foreach ($d in $dupIds) { Write-Host "  WARNING: duplicate talent affix id $($d.Name) found!" -ForegroundColor Yellow }
}

Write-Host "  Building SQL for $($talents.Count) talent affix(es) ..."

$sb = [System.Text.StringBuilder]::new()
$null = $sb.AppendLine("-- talent_affix_def.sql")
$null = $sb.AppendLine("-- AUTO-GENERATED by build_talent_affixes.ps1 - do not edit directly.")
$null = $sb.AppendLine("-- Maps:         talent_affixes/_maps.json")
$null = $sb.AppendLine("-- Spec entries: talent_affixes/<Class>/<spec>.json")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("CREATE TABLE IF NOT EXISTS ``talent_affix_def`` (")
$null = $sb.AppendLine("    ``id``             INT UNSIGNED    NOT NULL,")
$null = $sb.AppendLine("    ``name``           VARCHAR(64)     NOT NULL DEFAULT '',")
$null = $sb.AppendLine("    ``class_mask``     INT UNSIGNED    NOT NULL DEFAULT 0,     -- bit (1 << (classId-1)); 0 = any class")
$null = $sb.AppendLine("    ``spec_tree``      TINYINT         NOT NULL DEFAULT -1,    -- -1 = any spec; 0/1/2 = dominant tree")
$null = $sb.AppendLine("    ``max_rank``       TINYINT         NOT NULL DEFAULT 5,     -- talent's max rank in the game")
$null = $sb.AppendLine("    ``spell_family``   TINYINT         NOT NULL DEFAULT 0,     -- SpellFamilyName enum value")
$null = $sb.AppendLine("    ``family_flags0``  INT UNSIGNED    NOT NULL DEFAULT 0,     -- SpellClassOptions.SpellClassMask[0]")
$null = $sb.AppendLine("    ``family_flags1``  INT UNSIGNED    NOT NULL DEFAULT 0,")
$null = $sb.AppendLine("    ``family_flags2``  INT UNSIGNED    NOT NULL DEFAULT 0,")
$null = $sb.AppendLine("    ``carrier_spell``  INT UNSIGNED    NOT NULL DEFAULT 0,     -- a spell from this family")
$null = $sb.AppendLine("    ``spellmod_op``    TINYINT         NOT NULL DEFAULT 0,     -- SpellModOp value")
$null = $sb.AppendLine("    ``spellmod_type``  TINYINT UNSIGNED NOT NULL DEFAULT 107,  -- 107=FLAT  108=PCT")
$null = $sb.AppendLine("    ``value_per_rank`` INT             NOT NULL DEFAULT 0,     -- magnitude per rolled rank")
$null = $sb.AppendLine("    ``item_category``  TINYINT UNSIGNED NOT NULL DEFAULT 0,     -- AffixItemCategory: 0=any 8=DAGGER")
$null = $sb.AppendLine("    PRIMARY KEY (``id``)")
$null = $sb.AppendLine(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("-- Idempotent column addition (servers upgrading without DROP/CREATE)")
$null = $sb.AppendLine("SET @add_smt = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS")
$null = $sb.AppendLine("    WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='talent_affix_def' AND COLUMN_NAME='spellmod_type')=0,")
$null = $sb.AppendLine("    'ALTER TABLE ``talent_affix_def`` ADD COLUMN ``spellmod_type`` TINYINT UNSIGNED NOT NULL DEFAULT 107 AFTER ``spellmod_op``',")
$null = $sb.AppendLine("    'SELECT 1');")
$null = $sb.AppendLine("PREPARE _s FROM @add_smt; EXECUTE _s; DEALLOCATE PREPARE _s;")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("SET @add_ic = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS")
$null = $sb.AppendLine("    WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='talent_affix_def' AND COLUMN_NAME='item_category')=0,")
$null = $sb.AppendLine("    'ALTER TABLE ``talent_affix_def`` ADD COLUMN ``item_category`` TINYINT UNSIGNED NOT NULL DEFAULT 0',")
$null = $sb.AppendLine("    'SELECT 1');")
$null = $sb.AppendLine("PREPARE _s FROM @add_ic; EXECUTE _s; DEALLOCATE PREPARE _s;")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("-- ====================================================================")
$null = $sb.AppendLine("-- SpellModOp: DAMAGE=0 CRIT_CHANCE=7 CASTING_TIME=10 COOLDOWN=11")
$null = $sb.AppendLine("--             COST=14  RESIST_MISS_CHANCE=16  DOT_DURATION=22")
$null = $sb.AppendLine("-- SpellModType: 107=FLAT  108=PCT")
$null = $sb.AppendLine("-- class_mask: 1=Warrior 2=Paladin 4=Hunter 8=Rogue 16=Priest")
$null = $sb.AppendLine("--             32=DK 64=Shaman 128=Mage 256=Warlock 1024=Druid")
$null = $sb.AppendLine("-- ====================================================================")
$null = $sb.AppendLine("")

# Emit DELETE for any removed talent affixes
if ($allRemovedIds.Count -gt 0) {
    $uniqueRemovedIds = ($allRemovedIds | Sort-Object -Unique) -join ", "
    Write-Host "  Removing $($allRemovedIds.Count) retired talent affix id(s): $uniqueRemovedIds"
    $null = $sb.AppendLine("-- Remove talent affixes listed in removedTalentAffixes")
    $null = $sb.AppendLine("DELETE FROM ``talent_affix_def`` WHERE ``id`` IN ($uniqueRemovedIds);")
    $null = $sb.AppendLine("")
}

# Build INSERT rows
$rows = @()
$prevClass = ""
foreach ($t in $talents) {
    # Resolve string fields to numbers
    $classMask  = if ($t.class -match '^\d+$') { [int]$t.class } else { $classMaskMap[$t.class] }
    $family     = if ($t.spell_family -match '^\d+$') { [int]$t.spell_family } else { $familyMap[$t.spell_family] }
    $op         = if ($t.spellmod_op -match '^\d+$') { [int]$t.spellmod_op } else { $opMap[$t.spellmod_op] }
    $modType    = if ($t.spellmod_type -match '^\d+$') { [int]$t.spellmod_type } else { $typeMap[$t.spellmod_type] }

    $f0 = [long]$t.family_flags[0]
    $f1 = [long]$t.family_flags[1]
    $f2 = [long]$t.family_flags[2]

    # Section comment when class changes
    $cls = $t.class
    if ($cls -ne $prevClass) {
        if ($rows.Count -gt 0) { $rows += "" }   # blank line between classes
        $rows += "-- $cls"
        $prevClass = $cls
    }

    $nameSql  = $t.name -replace "'", "''"
    $itemCat  = if ($t.PSObject.Properties['item_category']) { [int]$t.item_category } else { 0 }
    $note     = if ($t.notes) { " -- $($t.notes)" } else { "" }
    $rows += "($($t.id), '$nameSql', $classMask, $($t.spec_tree), $($t.max_rank),  $family, $f0, $f1, $f2,  $($t.carrier_spell), $op, $modType, $($t.value_per_rank), $itemCat)$note"
}

$null = $sb.AppendLine("INSERT INTO ``talent_affix_def``")
$null = $sb.AppendLine("    (``id``, ``name``, ``class_mask``, ``spec_tree``, ``max_rank``,")
$null = $sb.AppendLine("     ``spell_family``, ``family_flags0``, ``family_flags1``, ``family_flags2``,")
$null = $sb.AppendLine("     ``carrier_spell``, ``spellmod_op``, ``spellmod_type``, ``value_per_rank``, ``item_category``)")
$null = $sb.AppendLine("VALUES")

for ($i = 0; $i -lt $rows.Count; $i++) {
    $r = $rows[$i]
    if ($r -eq "" -or $r.StartsWith("--")) {
        # Comment / blank line — emit as SQL comment before the next value row
        if ($r -ne "") { $null = $sb.AppendLine("-- $($r.TrimStart('-').Trim())") }
        continue
    }
    # Check if there's a non-comment, non-blank row after this one
    $hasMore = ($rows | Select-Object -Skip ($i+1) | Where-Object { $_ -ne "" -and -not $_.StartsWith("--") }).Count -gt 0
    $comma   = if ($hasMore) { "," } else { "" }
    # Place comma BEFORE any inline SQL comment so it isn't swallowed by the comment lexer.
    $noteIdx = $r.IndexOf(' -- ')
    if ($comma -ne "" -and $noteIdx -ge 0) {
        $null = $sb.AppendLine("$($r.Substring(0, $noteIdx))$comma$($r.Substring($noteIdx))")
    } else {
        $null = $sb.AppendLine("$r$comma")
    }
}

$null = $sb.AppendLine("ON DUPLICATE KEY UPDATE")
$null = $sb.AppendLine("    ``name``          = VALUES(``name``),")
$null = $sb.AppendLine("    ``class_mask``    = VALUES(``class_mask``),")
$null = $sb.AppendLine("    ``spec_tree``     = VALUES(``spec_tree``),")
$null = $sb.AppendLine("    ``max_rank``      = VALUES(``max_rank``),")
$null = $sb.AppendLine("    ``spell_family``  = VALUES(``spell_family``),")
$null = $sb.AppendLine("    ``family_flags0`` = VALUES(``family_flags0``),")
$null = $sb.AppendLine("    ``family_flags1`` = VALUES(``family_flags1``),")
$null = $sb.AppendLine("    ``family_flags2`` = VALUES(``family_flags2``),")
$null = $sb.AppendLine("    ``carrier_spell`` = VALUES(``carrier_spell``),")
$null = $sb.AppendLine("    ``spellmod_op``   = VALUES(``spellmod_op``),")
$null = $sb.AppendLine("    ``spellmod_type`` = VALUES(``spellmod_type``),")
$null = $sb.AppendLine("    ``value_per_rank`` = VALUES(``value_per_rank``),")
$null = $sb.AppendLine("    ``item_category``  = VALUES(``item_category``);")

$content = $sb.ToString()
$content | Out-File -FilePath $OutPath -Encoding utf8 -NoNewline
Write-Host "  Wrote $OutPath ($($talents.Count) entries)."
