# build_affixes.ps1
# Reads affixes/*.json and regenerates data/sql/db-world/affix_template.sql
# Run whenever you change affixes JSON, then run update_affixes.bat and restart worldserver.

param()

$scriptDir        = Split-Path -Parent $MyInvocation.MyCommand.Path
$moduleRoot       = Split-Path -Parent $scriptDir
$affixesDir       = Join-Path $moduleRoot "affixes"
$classAffixesDir  = Join-Path $moduleRoot "class_affixes"
$sqlPath          = Join-Path $moduleRoot "data\sql\db-world\affix_template.sql"

if (-not (Test-Path $affixesDir)) {
    Write-Error "affixes/ folder not found at $affixesDir"; exit 1
}
$classFiles = @(Get-ChildItem $affixesDir -Filter "*.json" | Sort-Object Name)
if (Test-Path $classAffixesDir) {
    $classFiles += @(Get-ChildItem $classAffixesDir -Filter "*.json" | Sort-Object Name)
}
if ($classFiles.Count -eq 0) {
    Write-Error "No .json files found in $affixesDir or $classAffixesDir"; exit 1
}
$allAffixes = [System.Collections.Generic.List[object]]::new()
$allRemoved = [System.Collections.Generic.List[object]]::new()

$genericDefs = $null

foreach ($file in $classFiles) {
    $classJson = Get-Content $file.FullName -Raw | ConvertFrom-Json
    if ($classJson._type -eq 'generic_defs') {
        $genericDefs = $classJson
        if ($classJson.removedAffixes) { $classJson.removedAffixes | ForEach-Object { $allRemoved.Add($_) } }
    } else {
        if ($classJson.affixes)        { $classJson.affixes        | ForEach-Object { $allAffixes.Add($_) } }
        if ($classJson.removedAffixes) { $classJson.removedAffixes | ForEach-Object { $allRemoved.Add($_) } }
    }
}

# Load generic stat affixes — values are computed at runtime from item budget (no tier files needed)
if ($genericDefs) {
    foreach ($def in $genericDefs.affixes) {
        if ($def.PSObject.Properties['enabled'] -and $def.enabled -eq $false) { continue }
        $defRole = if ($def.PSObject.Properties['role'] -and $def.role -ne "") { [string]$def.role } else { "" }
        $allAffixes.Add([PSCustomObject]@{
            id            = [int]$def.id
            family        = 0  # stat affixes don't target spells
            name          = $def.name
            weight        = [int]$def.weight
            min_quality   = [int]$def.min_quality
            affix_type    = 1
            stat          = $def.stat
            item_category = if ($def.PSObject.Properties['item_category']) { [int]$def.item_category } else { 0 }
            spec_tree     = if ($def.PSObject.Properties['spec_tree'])     { [int]$def.spec_tree }     else { 255 }
            role          = $defRole
            tooltip       = $def.tooltip
        })
    }
}

$opNames = @{
    0  = "SPELLMOD_DAMAGE"
    1  = "SPELLMOD_DURATION"
    2  = "SPELLMOD_THREAT"
    4  = "SPELLMOD_CHARGES"
    5  = "SPELLMOD_RANGE"
    7  = "SPELLMOD_CRITICAL_CHANCE"
    8  = "SPELLMOD_ALL_EFFECTS"
    10 = "SPELLMOD_CASTING_TIME"
    11 = "SPELLMOD_COOLDOWN"
    14 = "SPELLMOD_COST"
    15 = "SPELLMOD_CRIT_DAMAGE_BONUS"
    22 = "SPELLMOD_DOT"
    27 = "SPELLMOD_VALUE_MULTIPLIER"
}
$typeNames = @{ 107 = "FLAT"; 108 = "PCT" }

$statOpNames = @{
    0  = "STAMINA"; 1  = "STRENGTH"; 2  = "AGILITY"; 3  = "INTELLECT"; 4  = "SPIRIT"
    5  = "ATTACK_POWER"; 6  = "RANGED_AP"; 7  = "SPELL_POWER"; 8  = "MP5"; 9  = "ARMOR"
    10 = "CRIT_RATING"; 11 = "HASTE_RATING"; 12 = "HIT_RATING"; 13 = "DODGE_RATING"
    14 = "DEFENSE_RATING"; 15 = "PARRY_RATING"; 16 = "EXPERTISE_RATING"; 17 = "ARMOR_PEN_RATING"
    18 = "MOVE_SPEED"
}

$itemCatNames = @{
    0 = "ANY"; 1 = "WEAPON_1H"; 2 = "WEAPON_2H"; 3 = "WEAPON"
    4 = "ARMOR"; 5 = "JEWELRY"; 6 = "WAND"; 7 = "BOOTS"; 8 = "DAGGER"
}

$roleMap = @{
    "CASTER"         = 1
    "PHYSICAL"       = 2
    "TANK"           = 4
    "HEALER"         = 8
    "RANGED"          = 16
    "CASTER_HEALER"   = 9   # 1|8
    "PHYSICAL_TANK"   = 6   # 2|4
    "PHYSICAL_RANGED" = 18  # 2|16
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("-- ============================================================")
$lines.Add("-- affix_template.sql")
$lines.Add("-- AUTO-GENERATED by build_affixes.ps1 from affixes/")
$lines.Add("-- DO NOT edit this file directly -- edit the affixes/ JSON files instead")
$lines.Add("-- ============================================================")
$lines.Add("")
$lines.Add("CREATE TABLE IF NOT EXISTS ``affix_template`` (")
$lines.Add("  ``id``                   INT UNSIGNED     NOT NULL,")
$lines.Add("  ``name``                 VARCHAR(64)      NOT NULL DEFAULT '',")
$lines.Add("  ``weight``               INT UNSIGNED     NOT NULL DEFAULT 100,")
$lines.Add("  ``min_quality``          TINYINT UNSIGNED NOT NULL DEFAULT 1,")
$lines.Add("  ``spellmod_op``          TINYINT UNSIGNED NOT NULL,")
$lines.Add("  ``spellmod_type``        SMALLINT UNSIGNED NOT NULL,")
$lines.Add("  ``spellmod_value``       INT              NOT NULL,")
$lines.Add("  ``spell_family``         INT UNSIGNED     NOT NULL,")
$lines.Add("  ``spell_family_flags0``  INT UNSIGNED     NOT NULL DEFAULT 0,")
$lines.Add("  ``spell_family_flags1``  INT UNSIGNED     NOT NULL DEFAULT 0,")
$lines.Add("  ``spell_family_flags2``  INT UNSIGNED     NOT NULL DEFAULT 0,")
$lines.Add("  ``carrier_spell_id``     INT UNSIGNED     NOT NULL,")
$lines.Add("  ``enchant_id``           INT UNSIGNED     NOT NULL DEFAULT 0,")
$lines.Add("  ``spellmod_op2``         TINYINT UNSIGNED  NOT NULL DEFAULT 255,")
$lines.Add("  ``spellmod_type2``       SMALLINT UNSIGNED NOT NULL DEFAULT 107,")
$lines.Add("  ``spellmod_value2``      INT               NOT NULL DEFAULT 0,")
$lines.Add("  ``spellmod_op3``         TINYINT UNSIGNED  NOT NULL DEFAULT 255,")
$lines.Add("  ``spellmod_type3``       SMALLINT UNSIGNED NOT NULL DEFAULT 107,")
$lines.Add("  ``spellmod_value3``      INT               NOT NULL DEFAULT 0,")
$lines.Add("  ``spellmod_op4``         TINYINT UNSIGNED  NOT NULL DEFAULT 255,")
$lines.Add("  ``spellmod_type4``       SMALLINT UNSIGNED NOT NULL DEFAULT 107,")
$lines.Add("  ``spellmod_value4``      INT               NOT NULL DEFAULT 0,")
$lines.Add("  ``affix_type``           TINYINT UNSIGNED  NOT NULL DEFAULT 0,")
$lines.Add("  ``stat_op``              TINYINT UNSIGNED  NOT NULL DEFAULT 0,")
$lines.Add("  ``stat_tiers``           VARCHAR(255)      NOT NULL DEFAULT '',")
$lines.Add("  ``level_min``            TINYINT UNSIGNED  NOT NULL DEFAULT 1,")
$lines.Add("  ``level_max``            TINYINT UNSIGNED  NOT NULL DEFAULT 80,")
$lines.Add("  ``item_category``        TINYINT UNSIGNED  NOT NULL DEFAULT 0,")
$lines.Add("  ``spec_tree``            TINYINT UNSIGNED  NOT NULL DEFAULT 255,")
$lines.Add("  ``role_mask``            TINYINT UNSIGNED  NOT NULL DEFAULT 0,")
$lines.Add("  PRIMARY KEY (``id``)")
$lines.Add(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
$lines.Add("")
$lines.Add("CREATE TABLE IF NOT EXISTS ``spell_swap_chain_spells`` (")
$lines.Add("  ``affix_id``    INT UNSIGNED     NOT NULL,")
$lines.Add("  ``chain_count`` TINYINT UNSIGNED NOT NULL,")
$lines.Add("  ``solo_spell``  INT UNSIGNED     NOT NULL DEFAULT 0,")
$lines.Add("  ``combo_spell`` INT UNSIGNED     NOT NULL DEFAULT 0,")
$lines.Add("  PRIMARY KEY (``affix_id``, ``chain_count``)")
$lines.Add(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
$lines.Add("")

# Idempotent ALTER blocks — spellmod multi-effect columns
$lines.Add("-- Idempotent ALTERs: add columns to existing tables (MySQL 5.7+ / MariaDB)")
foreach ($col in @(
    @{ n="spellmod_op2";   t="TINYINT UNSIGNED NOT NULL DEFAULT 255" },
    @{ n="spellmod_type2"; t="SMALLINT UNSIGNED NOT NULL DEFAULT 107" },
    @{ n="spellmod_value2";t="INT NOT NULL DEFAULT 0" },
    @{ n="spellmod_op3";   t="TINYINT UNSIGNED NOT NULL DEFAULT 255" },
    @{ n="spellmod_type3"; t="SMALLINT UNSIGNED NOT NULL DEFAULT 107" },
    @{ n="spellmod_value3";t="INT NOT NULL DEFAULT 0" },
    @{ n="spellmod_op4";   t="TINYINT UNSIGNED NOT NULL DEFAULT 255" },
    @{ n="spellmod_type4"; t="SMALLINT UNSIGNED NOT NULL DEFAULT 107" },
    @{ n="spellmod_value4";t="INT NOT NULL DEFAULT 0" },
    @{ n="affix_type";     t="TINYINT UNSIGNED NOT NULL DEFAULT 0" },
    @{ n="stat_op";        t="TINYINT UNSIGNED NOT NULL DEFAULT 0" },
    @{ n="stat_tiers";     t="VARCHAR(255) NOT NULL DEFAULT ''''" },
    @{ n="level_min";      t="TINYINT UNSIGNED NOT NULL DEFAULT 1" },
    @{ n="level_max";      t="TINYINT UNSIGNED NOT NULL DEFAULT 80" },
    @{ n="item_category";  t="TINYINT UNSIGNED NOT NULL DEFAULT 0" },
    @{ n="spec_tree";      t="TINYINT UNSIGNED NOT NULL DEFAULT 255" },
    @{ n="role_mask";      t="TINYINT UNSIGNED NOT NULL DEFAULT 0" }
)) {
    $varName = "@add_$($col.n -replace '[^a-zA-Z0-9]','_')"
    $lines.Add("SET $varName = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS")
    $lines.Add("    WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='affix_template' AND COLUMN_NAME='$($col.n)')=0,")
    $lines.Add("    'ALTER TABLE ``affix_template`` ADD COLUMN ``$($col.n)`` $($col.t)',")
    $lines.Add("    'SELECT 1');")
    $lines.Add("PREPARE _s FROM $varName; EXECUTE _s; DEALLOCATE PREPARE _s;")
    $lines.Add("")
}

# Delete affixes listed in removedAffixes (history kept in JSON, removed from DB)
if ($allRemoved -and $allRemoved.Count -gt 0) {
    $removedIds = @($allRemoved | Where-Object { $null -ne $_.id } | ForEach-Object { [int]$_.id } | Sort-Object -Unique)
    if ($removedIds.Count -gt 0) {
        $idList = $removedIds -join ', '
        $lines.Add("-- Remove affixes moved to removedAffixes")
        $lines.Add("DELETE FROM ``affix_template`` WHERE ``id`` IN ($idList);")
        $lines.Add("")
    }
}

$chainSpellRows = [System.Collections.Generic.List[object]]::new()

foreach ($affix in $allAffixes) {
    # Skip disabled entries (enabled: false flag)
    if ($affix.PSObject.Properties['enabled'] -and $affix.enabled -eq $false) {
        continue
    }

    $isStatAffix  = ($affix.PSObject.Properties['affix_type'] -and [int]$affix.affix_type -eq 1)
    $isSpellSwap  = ($affix.PSObject.Properties['affix_type'] -and [int]$affix.affix_type -eq 2)

    if ($isSpellSwap) {
        # ---- spell-swap affix path ----
        # spellmod columns are repurposed: op=swap_group, value=solo_spell, value2=combo_spell
        # carrier_spell_id = base spell to replace; stat_op = swap role (1=chain, 2=mark)
        $swapGroup  = [int]$affix.swap.swap_group
        $soloSpell  = [int]$affix.swap.solo_spell
        $comboSpell = [int]$affix.swap.combo_spell
        $swapRole   = [int]$affix.swap.swap_role
        $baseSpell  = [int]$affix.swap.base_spell
        $family     = [int]$affix.family
        $f0 = [int]$affix.flags[0];  $f1 = [int]$affix.flags[1];  $f2 = [int]$affix.flags[2]
        $itemCat    = 0
        $specTree   = if ($affix.PSObject.Properties['spec_tree']) { [int]$affix.spec_tree } else { 255 }
        $roleMask   = 0
        $statOp     = $swapRole
        $carrierId  = $baseSpell
        $enchantId  = [int]$affix.tooltip.enchant_id
        $statTiersStr = ""
        $levelMin = 1;  $levelMax = 80
        $affixType = 2
        $op  = $swapGroup;  $typ  = 107;  $val  = $soloSpell
        $op2 = 255;         $typ2 = 107;  $val2 = $comboSpell
        $op3 = 255;         $typ3 = 107;  $val3 = 0
        $op4 = 255;         $typ4 = 107;  $val4 = 0

        # Collect chain_spells entries for the spell_swap_chain_spells table
        if ($affix.swap.PSObject.Properties['chain_spells']) {
            $countIdx = 1
            foreach ($pair in $affix.swap.chain_spells) {
                $chainSpellRows.Add([PSCustomObject]@{
                    affixId    = [int]$affix.id
                    chainCount = $countIdx
                    soloSpell  = [int]$pair[0]
                    comboSpell = [int]$pair[1]
                })
                $countIdx++
            }
        }

        $lines.Add("-- ----------------------------------------------------------------")
        $lines.Add("-- Affix $($affix.id): $($affix.name)  [SPELL_SWAP]")
        $lines.Add("-- Base : $baseSpell -> Solo: $soloSpell | Combo: $comboSpell")
        $lines.Add("-- Group: $swapGroup | Role: $swapRole | Family: $family | Flags: [$f0, $f1, $f2]")
        $lines.Add("-- ----------------------------------------------------------------")
    } elseif ($isStatAffix) {
        # ---- stat affix path ----
        $statOp      = [int]$affix.stat.op
        $statOpLabel = if ($statOpNames.ContainsKey($statOp)) { $statOpNames[$statOp] } else { "op=$statOp" }
        $itemCat     = if ($affix.PSObject.Properties['item_category']) { [int]$affix.item_category } else { 0 }
        $specTree    = if ($affix.PSObject.Properties['spec_tree'])     { [int]$affix.spec_tree }     else { 255 }
        $roleMask    = if ($affix.PSObject.Properties['role'] -and $affix.role -ne "") { if ($roleMap.ContainsKey([string]$affix.role)) { $roleMap[[string]$affix.role] } else { 0 } } else { 0 }
        $catLabel    = if ($itemCatNames.ContainsKey($itemCat)) { $itemCatNames[$itemCat] } else { "cat=$itemCat" }

        # Stat values are computed at runtime from item budget — no tier data stored.
        $statTiersStr = ""
        $levelMin     = 1
        $levelMax     = 80

        # Sentinel values for unused spellmod fields
        $op  = 255; $typ  = 107; $val  = 0
        $op2 = 255; $typ2 = 107; $val2 = 0
        $op3 = 255; $typ3 = 107; $val3 = 0
        $op4 = 255; $typ4 = 107; $val4 = 0
        $family   = if ($affix.PSObject.Properties['family']) { [int]$affix.family } else { [int]$affix.target.family }
        $f0 = 0; $f1 = 0; $f2 = 0
        $carrierId   = 0
        $enchantId   = if ($affix.PSObject.Properties['tooltip'] -and $affix.tooltip.enchant_id) { [int]$affix.tooltip.enchant_id } else { 0 }
        $affixType   = 1

        $lines.Add("-- ----------------------------------------------------------------")
        $lines.Add("-- Affix $($affix.id): $($affix.name)")
        $lines.Add("-- Family : $family | ItemCat: $catLabel | SpecTree: $specTree")
        $lines.Add("-- Effect : STAT/$statOpLabel (budget-computed at runtime)")
        $lines.Add("-- ----------------------------------------------------------------")
    } else {
        # ---- spellmod affix path (existing logic) ----
        $op        = [int]$affix.effect.op
        $typ       = [int]$affix.effect.modifier
        $opLabel   = if ($opNames.ContainsKey($op))  { $opNames[$op]  } else { "op=$op" }
        $typeLabel = if ($typeNames.ContainsKey($typ)) { $typeNames[$typ] } else { "type=$typ" }
        $verified  = if ($affix.target.verified) { "VERIFIED" } else { "UNVERIFIED -- run: $($affix.target.verify_command)" }
        $f0 = $affix.target.flags[0]
        $f1 = $affix.target.flags[1]
        $f2 = $affix.target.flags[2]
        $hex0 = if ($affix.target.flags_hex) { $affix.target.flags_hex[0] } else { "0x{0:X8}" -f [int64]$f0 }
        $hex1 = if ($affix.target.flags_hex) { $affix.target.flags_hex[1] } else { "0x{0:X8}" -f [int64]$f1 }
        $hex2 = if ($affix.target.flags_hex) { $affix.target.flags_hex[2] } else { "0x{0:X8}" -f [int64]$f2 }

        $op2  = if ($affix.effect2) { [int]$affix.effect2.op }       else { 255 }
        $typ2 = if ($affix.effect2) { [int]$affix.effect2.modifier }  else { 107 }
        $val2 = if ($affix.effect2) { [int]$affix.effect2.value }     else { 0 }
        $op3  = if ($affix.effect3) { [int]$affix.effect3.op }       else { 255 }
        $typ3 = if ($affix.effect3) { [int]$affix.effect3.modifier }  else { 107 }
        $val3 = if ($affix.effect3) { [int]$affix.effect3.value }     else { 0 }
        $op4  = if ($affix.effect4) { [int]$affix.effect4.op }       else { 255 }
        $typ4 = if ($affix.effect4) { [int]$affix.effect4.modifier }  else { 107 }
        $val4 = if ($affix.effect4) { [int]$affix.effect4.value }     else { 0 }

        $extraEffects = @()
        foreach ($e in @(
            @{ n=2; op=$op2; typ=$typ2; val=$val2 },
            @{ n=3; op=$op3; typ=$typ3; val=$val3 },
            @{ n=4; op=$op4; typ=$typ4; val=$val4 }
        )) {
            if ($e.op -ne 255) {
                $l = if ($opNames.ContainsKey($e.op))   { $opNames[$e.op]   } else { "op=$($e.op)"   }
                $t = if ($typeNames.ContainsKey($e.typ)) { $typeNames[$e.typ] } else { "type=$($e.typ)" }
                $extraEffects += "Effect$($e.n): $l ($t) value=$($e.val)"
            }
        }
        $effect2Label = if ($extraEffects.Count -gt 0) { " | $($extraEffects -join ' | ')" } else { "" }

        $carrierId    = $affix.target.carrier_spell_id
        $enchantId    = $affix.tooltip.enchant_id
        $family       = $affix.target.family
        $itemCat      = if ($affix.PSObject.Properties['item_category']) { [int]$affix.item_category } else { 0 }
        $specTree     = if ($affix.PSObject.Properties['spec_tree']) { [int]$affix.spec_tree } else { 255 }
        $roleMask     = 0
        $statOp       = 0
        $statTiersStr = ""
        $levelMin     = 1
        $levelMax     = 80
        $affixType    = 0

        $lines.Add("-- ----------------------------------------------------------------")
        $lines.Add("-- Affix $($affix.id): $($affix.name)")
        $lines.Add("-- Target : $($affix.target.description)")
        $lines.Add("-- Flags  : [$hex0, $hex1, $hex2]")
        $lines.Add("-- Effect : $opLabel ($typeLabel) value=$($affix.effect.value)$effect2Label")
        $lines.Add("-- Verify : $verified")
        $lines.Add("-- ----------------------------------------------------------------")
    }

    $safeName = $affix.name -replace "'", "''"
    $lines.Add("INSERT INTO ``affix_template``")
    $lines.Add("    (id, name, weight, min_quality, spellmod_op, spellmod_type, spellmod_value,")
    $lines.Add("     spell_family, spell_family_flags0, spell_family_flags1, spell_family_flags2,")
    $lines.Add("     carrier_spell_id, enchant_id,")
    $lines.Add("     spellmod_op2, spellmod_type2, spellmod_value2,")
    $lines.Add("     spellmod_op3, spellmod_type3, spellmod_value3,")
    $lines.Add("     spellmod_op4, spellmod_type4, spellmod_value4,")
    $lines.Add("     affix_type, stat_op, stat_tiers, level_min, level_max, item_category, spec_tree, role_mask)")
    $lines.Add("VALUES")
    if ($isStatAffix -or $isSpellSwap) {
        $lines.Add("    ($($affix.id), '$safeName', $($affix.weight), $($affix.min_quality), $op, $typ, $val,")
        $lines.Add("     $family, $f0, $f1, $f2,")
        $lines.Add("     $carrierId, $enchantId,")
        $lines.Add("     $op2, $typ2, $val2,")
        $lines.Add("     $op3, $typ3, $val3,")
        $lines.Add("     $op4, $typ4, $val4,")
        $lines.Add("     $affixType, $statOp, '$statTiersStr', $levelMin, $levelMax, $itemCat, $specTree, $roleMask)")
    } else {
        $lines.Add("    ($($affix.id), '$safeName', $($affix.weight), $($affix.min_quality), $op, $typ, $($affix.effect.value),")
        $lines.Add("     $family, $f0, $f1, $f2,")
        $lines.Add("     $carrierId, $enchantId,")
        $lines.Add("     $op2, $typ2, $val2,")
        $lines.Add("     $op3, $typ3, $val3,")
        $lines.Add("     $op4, $typ4, $val4,")
        $lines.Add("     $affixType, $statOp, '$statTiersStr', $levelMin, $levelMax, $itemCat, $specTree, $roleMask)")
    }
    $lines.Add("ON DUPLICATE KEY UPDATE")
    $lines.Add("    name = VALUES(name),")
    $lines.Add("    weight = VALUES(weight),")
    $lines.Add("    min_quality = VALUES(min_quality),")
    $lines.Add("    spellmod_op = VALUES(spellmod_op),")
    $lines.Add("    spellmod_type = VALUES(spellmod_type),")
    $lines.Add("    spellmod_value = VALUES(spellmod_value),")
    $lines.Add("    spell_family = VALUES(spell_family),")
    $lines.Add("    spell_family_flags0 = VALUES(spell_family_flags0),")
    $lines.Add("    spell_family_flags1 = VALUES(spell_family_flags1),")
    $lines.Add("    spell_family_flags2 = VALUES(spell_family_flags2),")
    $lines.Add("    carrier_spell_id = VALUES(carrier_spell_id),")
    $lines.Add("    enchant_id = VALUES(enchant_id),")
    $lines.Add("    spellmod_op2 = VALUES(spellmod_op2),")
    $lines.Add("    spellmod_type2 = VALUES(spellmod_type2),")
    $lines.Add("    spellmod_value2 = VALUES(spellmod_value2),")
    $lines.Add("    spellmod_op3 = VALUES(spellmod_op3),")
    $lines.Add("    spellmod_type3 = VALUES(spellmod_type3),")
    $lines.Add("    spellmod_value3 = VALUES(spellmod_value3),")
    $lines.Add("    spellmod_op4 = VALUES(spellmod_op4),")
    $lines.Add("    spellmod_type4 = VALUES(spellmod_type4),")
    $lines.Add("    spellmod_value4 = VALUES(spellmod_value4),")
    $lines.Add("    affix_type = VALUES(affix_type),")
    $lines.Add("    stat_op = VALUES(stat_op),")
    $lines.Add("    stat_tiers = VALUES(stat_tiers),")
    $lines.Add("    level_min = VALUES(level_min),")
    $lines.Add("    level_max = VALUES(level_max),")
    $lines.Add("    item_category = VALUES(item_category),")
    $lines.Add("    spec_tree = VALUES(spec_tree),")
    $lines.Add("    role_mask = VALUES(role_mask);")
    $lines.Add("")
}

# Emit spell_swap_chain_spells data collected from all chain_spells arrays
if ($chainSpellRows.Count -gt 0) {
    $affixIdList = (($chainSpellRows | Select-Object -ExpandProperty affixId -Unique) -join ',')
    $lines.Add("-- spell_swap_chain_spells: chain-count variant spell IDs for SPELL_SWAP affixes")
    $lines.Add("DELETE FROM ``spell_swap_chain_spells`` WHERE ``affix_id`` IN ($affixIdList);")
    $lines.Add("INSERT INTO ``spell_swap_chain_spells`` (``affix_id``, ``chain_count``, ``solo_spell``, ``combo_spell``) VALUES")
    $rowParts = [System.Collections.Generic.List[string]]::new()
    foreach ($row in $chainSpellRows) {
        $rowParts.Add("    ($($row.affixId), $($row.chainCount), $($row.soloSpell), $($row.comboSpell))")
    }
    $lines.Add(($rowParts -join ",`r`n") + ";")
    $lines.Add("")
}

$enc = [System.Text.UTF8Encoding]::new($false)  # UTF-8 no BOM
$sql = $lines -join "`r`n"
[System.IO.File]::WriteAllText($sqlPath, $sql, $enc)
Write-Host "Generated: $sqlPath"
$enabled = @($allAffixes | Where-Object { -not ($_.PSObject.Properties['enabled'] -and $_.enabled -eq $false) })
Write-Host "  $($enabled.Count) affix(es) written ($($allAffixes.Count - $enabled.Count) skipped/disabled) from $($classFiles.Count) file(s)."
Write-Host ""
Write-Host "Next: run update_affixes.bat, then restart worldserver."
